sudo: required
cache:
  - pip
  - ccache
notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - FUNQ_CXXFLAGS="-Wall -Wextra -Werror"  # make CI fail on warnings

matrix:
  fast_finish: true
  include:

    # MacOS Qt5 Python2
    - os: osx
      language: cpp
      env: QT_SELECT=5 PYTHON=python2

    # MacOS Qt5 Python3
    - os: osx
      language: cpp
      env: QT_SELECT=5 PYTHON=python3

    # Linux Qt4 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=4 PYTHON=python

    # Linux Qt4 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=4 PYTHON=python

    # Linux Qt5.2.1 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=5.2.1 PYTHON=python

    # Linux Qt5.3.2 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=5.3.2 PYTHON=python

    # Linux Qt5.4.2 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=5.4.2 PYTHON=python

    # Linux Qt5.5.1 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=5.5.1 PYTHON=python

    # Linux Qt5.6.3 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=5.6.3 PYTHON=python

    # Linux Qt5.7.1 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=5.7.1 PYTHON=python


    # Linux Qt5.8 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=5.8 PYTHON=python

    # Linux Qt5.9.6 Python3.4
    - os: linux
      dist: trusty
      language: python
      python: 3.4
      env: QT_SELECT=5.9.6 PYTHON=python

    # Linux Qt5.10.1 Python2.7
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      env: QT_SELECT=5.10.1 PYTHON=python

install:
  - source ./ci/install_dependencies.sh # source required because of exports
  - $PYTHON --version                   # check exact python version
  - qmake --version                     # check exact Qt version

script:
  - flake8 client/funq server/funq_server
  - cd client && $PYTHON setup.py develop && cd ..
  - cd server && $PYTHON setup.py develop && cd ..
  - cd server/tests && qmake QMAKE_CXXFLAGS="$FUNQ_CXXFLAGS" && make -j4 && cd ../..
  - cd tests-functionnal/funq-test-app && qmake QMAKE_CXXFLAGS="$FUNQ_CXXFLAGS" && make -j4 && cd ../..
  - cd client && $PYTHON setup.py test; cd ..
  - make -C server/tests/ check
  - cd tests-functionnal && nosetests && cd ..
